datasources:
  default:
    password: ''
    url: jdbc:mysql://localhost:3306/expenses?createDatabaseIfNotExist=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  application:
    name: expenses
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
spring:
  jpa:
    hibernate:
      ddl-auto: update